extends:
  - eslint-config-dmitmel/presets/node
  - eslint-config-dmitmel/presets/formatting
  - ./node_modules/ultimate-crosscode-typedefs/eslint-globals.js
env:
  browser: true
  node: true
parserOptions:
  sourceType: module

rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport
